export type Lead = {
  id: string;
  address: string;
  city: string;
  zip: string;
  county: string;
  lat: number;
  lng: number;
  propertyType: "single-family" | "multi-family" | "duplex" | "triplex" | "fourplex";
  units: number;
  beds: number;
  baths: number;
  sqft: number;
  yearBuilt: number;
  lastSaleDate: string;
  lastSalePrice: number;
  estimatedValue: number;
  estimatedEquity: number;
  equityPercent: number;
  taxDelinquent: boolean;
  preForeclosure: boolean;
  probate: boolean;
  codeViolations: boolean;
  vacant: boolean;
  absenteeOwner: boolean;
  motivationScore: number;
  scoreReasoning: string;
  suggestedOpener: string;
  status: "new" | "contacted" | "responded" | "under-contract" | "dead";
  assignedTo: string;
  lastContactedDate: string | null;
  notes: string;
  ownerName: string;
  ownerOccupied: boolean;
};
